- alias: Alarm clock on
  trigger:
    platform: mqtt
    topic: alarm_clock
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_wake_up
  id: f93d16b45e3845afb9c7733d86cb9f5f
- action:
  - alias: Plant Light on
    data:
      entity_id: light.plants
    service: light.turn_on
  alias: Sunrise Plants on
  condition: []
  id: '1509791350740'
  trigger:
  - event: sunrise
    platform: sun
- action:
  - alias: Plant Light off
    data:
      entity_id: light.plants
    service: light.turn_off
  alias: Sunset Plants off
  condition: []
  id: '1509791350741'
  trigger:
  - event: sunset
    platform: sun
- action:
  - alias: PC Room Light Off
    data:
      entity_id: group.pc_room_lights
    service: light.turn_off
  alias: PC Off Lights Off
  condition:
  - after: sunset
    condition: sun
  id: '1509918759411'
  trigger:
  - entity_id: device_tracker.xmbombpc
    from: home
    platform: state
    to: not_home
- action:
  - alias: PC Off TV Off
    data:
      entity_id: switch.tv
    service: switch.turn_off
  alias: PC Off TV Off
  id: pc-off-tv-off
  trigger:
  - entity_id: device_tracker.xmbombpc
    from: home
    platform: state
    to: not_home
- action:
  - alias: PC on TV on
    data:
      entity_id: switch.tv
    service: switch.turn_on
  alias: PC on TV on
  id: pc-on-tv-on
  trigger:
  - entity_id: device_tracker.xmbombpc
    from: not_home
    platform: state
    to: home
- action:
  - data:
      message: UPS DOWN!
    service: notify.pushbullet
  alias: UPS On Battery Notification
  condition: []
  id: '1511111478419'
  trigger:
  - entity_id: sensor.ups_status
    from: ONLINE
    platform: state
- action:
  - data:
      message: Schildkröten zu kalt
    service: notify.pushbullet_lis
  alias: Tortoises too cold
  condition: []
  id: '1511111478420'
  trigger:
  - entity_id: binary_sensor.shed_temperature_below_35
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      message: Schildkröten zu warm
    service: notify.pushbullet_lis
  alias: Tortoises too warm
  condition: []
  id: '1511111478421'
  trigger:
  - entity_id: binary_sensor.shed_temperature_above_10
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      color_name: red
      entity_id: light.desk_leds
    service: light.turn_on
  alias: Desk LEDs red if turned on after sunset
  condition:
  - after: sunset
    condition: sun
  id: '1520076564952'
  trigger:
  - entity_id: light.desk_leds
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      color_name: blue
      entity_id: light.desk_leds
    service: light.turn_on
  alias: Desk LED blue if turned on before sunset
  condition:
  - before: sunset
    condition: sun
  id: '1520076624811'
  trigger:
  - entity_id: light.desk_leds
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      message: ZMain Degraded
    service: notify.pushbullet
  alias: ZMain Degraded Notification
  condition: []
  id: '1511111478420'
  trigger:
  - entity_id: zfs.zmain_health
    from: ONLINE
    to: DEGRADED
    platform: state
- action:
  - data:
      message: ZBackup Degraded
    service: notify.pushbullet
  alias: ZBackup Degraded Notification
  condition: []
  id: '1511111478420'
  trigger:
  - entity_id: zfs.zbackup_health
    from: ONLINE
    to: DEGRADED
    platform: state
- action:
  - data:
      entity_id: switch.humidifier
    service: switch.turn_on
  alias: PC Room Humidifier On
  condition:
  - condition: state
    entity_id: group.milan_portable_devices
    state: home
  id: '1522953892250'
  trigger:
  - below: '45'
    entity_id: sensor.pc_room_humidity
    platform: numeric_state
- action:
  - data:
      entity_id: switch.humidifier
    service: switch.turn_off
  alias: PC Room Humidifier off
  condition:
  - condition: state
    entity_id: group.milan_portable_devices
    state: home
  id: '1522954007709'
  trigger:
  - above: '45'
    entity_id: sensor.pc_room_humidity
    platform: numeric_state
- id: '1527534824288'
  alias: Desk LED Red if turned on and after sunset
  trigger:
  - event: sunset
    platform: sun
  condition:
  - condition: state
    entity_id: light.desk_leds
    state: 'on'
  action:
  - data:
      color_name: red
      entity_id: light.desk_leds
    service: light.turn_on
- id: '1537640292472'
  alias: Grower on
  trigger:
  - at: '9:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id:
      - light.kitchen_grower
      - light.hydro_2700k
    service: light.turn_on
- id: '1537640537656'
  alias: Grower off
  trigger:
  - at: '20:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id:
      - light.kitchen_grower
    service: light.turn_off
- alias: 2700K off
  trigger:
  - platform: time
    at: '20:00'
  condition: []
  action:
  - data:
      entity_id:
      - light.hydro_2700k
    service: light.turn_off
  id: 2a508e9e53344e35bd4accb6fec1cab4
- alias: LG OLED paused/stopped
  trigger:
  - platform: state
    entity_id: media_player.lg_4k_oled
    from: 'playing'
    to: 'paused'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: scene.turn_on
    entity_id: scene.living_room_normal
  id: 1daa736598934a179c35e6567ab173d0
- alias: LG OLED off after playing
  trigger:
  - platform: state
    entity_id: media_player.lg_4k_oled
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: scene.turn_on
    entity_id: scene.living_room_normal
  id: 1daa736598934a179c35e6567ab173d0
- alias: LG OLED playing
  trigger:
  - platform: state
    entity_id: media_player.lg_4k_oled
    to: playing
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: scene.turn_on
    entity_id: scene.watching_tv
  id: 7d0974f0e61643c3bad60f08f6923f8e
- alias: Cameras off if home
  trigger:
  - platform: state
    entity_id: group.milan_and_linda
    to: home
    from: not_home
  action:
    service: switch.turn_off
    entity_id: group.fang_switches
  id: bdb1d72900f9459d8f3bbf0356b6bee1
- alias: Cameras on if not home
  trigger:
  - platform: state
    entity_id: group.milan_and_linda
    to: not_home
    from: home
  action:
    service: switch.turn_on
    entity_id: group.fang_switches
  id: 5592c91d1d054c4485d26e673df10216
- alias: Lights off if not home
  trigger:
  - platform: state
    entity_id: group.milan_and_linda
    to: not_home
    from: home
  action:
    service: light.turn_off
    entity_id: group.non_automatic_lights
  id: 25131da67fea4f56944935414680b6d1
- id: fbcbbbf751a84c0cb99e7a709aba8672
  alias: Lights on if home
  trigger:
  - entity_id: group.milan_and_linda
    from: not_home
    platform: state
    to: home
  condition:
  - after: sunset
    condition: sun
  action:
  - entity_id: group.evening_lights
    service: light.turn_on
- id: 744b4b893020470d85a9a4f841d5114c
  alias: alarm clock
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.bedroom_alarm_clock_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: state
    entity_id: device_tracker.galaxynote8
    state: home
  action:
  - entity_id: scene.bedroom_wake_up
    service: scene.turn_on
- alias: bed set
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.bed_mass
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.bed_mass
      above: 50
      below: 100
    - condition: state
      entity_id: device_tracker.galaxynote8
      state: home
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.in_bed
  id: a94c73122e7f4449bd600945188a3459
- alias: bed clear
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.bed_mass
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.bed_mass
      below: 20
    - condition: state
      entity_id: device_tracker.galaxynote8
      state: home
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.in_bed
  id: 0b1a7bfdca5445dda5672f4987d1ec12
- alias: Bed Occupied Tasks
  trigger:
    platform: state
    entity_id: input_boolean.in_bed
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '22:00:00'
      before: 04:00:00
    - condition: state
      entity_id: device_tracker.huawei_p10
      state: not_home
  action:
  - service: light.turn_off
    entity_id: group.non_automatic_lights
    data:
      transition: 10
  id: 39542d047c5245e7a008c59c9f1385db
- id: '1541266912466'
  alias: Hydro Bubbler on
  trigger:
  - entity_id: group.milan_and_linda
    platform: state
    to: not_home
  condition:
  - after: 06:00
    before: '22:00'
    condition: time
  action:
  - data:
      entity_id: switch.hydro_bubbler
    service: switch.turn_on
- id: '1541266912468'
  alias: Hydro Bubbler off
  trigger:
  - entity_id: device_tracker.galaxynote8
    platform: state
    to: home
  action:
  - data:
      entity_id: switch.hydro_bubbler
    service: switch.turn_off
- id: lightByTime
  alias: Set light level by time of day
  trigger:
    platform: state
    from: 'off'
    to: 'on'
    entity_id:
    - light.bed_leds
    - light.bedroom_corner
    - light.bedroom_corner_2
    - light.bedroom_panel
    - light.desk_leds
    - light.hallway_panel
    - light.kitchen_panel
    - light.living_room_panel
    - light.living_room_sofa
    - light.living_room_dinner_table
    - light.pc_room_monitors_2
    - light.pc_room_monitors_3
    - light.pc_room_panel_3
    - light.tradfri_bulb_e27_ws_opal_980lm_4
    - light.tv_leds
    - light.sofa_leds
  action:
    data_template:
      brightness: '{% if is_state(''sun.sun'', ''below_horizon'') %}30{% else %}200{%
        endif %}'
      color_temp: '{% if is_state(''sun.sun'', ''below_horizon'') %}454{% else %}1{%
        endif %}'
      entity_id: '{{trigger.entity_id}}'
    service: light.turn_on
- alias: Pause TV if light is turned on in another room
  trigger:
    platform: state
    from: 'off'
    to: 'on'
    entity_id: group.non_living_room_lights
  condition: 
    - condition: state
      entity_id: media_player.lg_4k_oled
      state: 'playing'
  action:
    service: media_player.media_pause
    entity_id: media_player.lg_4k_oled
