- alias: Hass start
  trigger:
    platform: homeassistant
    event: start
  hide_entity: true
  action:
  - service: switch.turn_on
    entity_id: switch.flux
  id: 06e20ecadc174fe5983f810e9a3ca984
- alias: MQTT Alarm clock
  trigger:
    platform: mqtt
    topic: alarm_clock
  action:
    service: scene.turn_on
    entity_id: scene.bedroom_wake_up
  id: f93d16b45e3845afb9c7733d86cb9f5f
- action:
  - alias: Plant Light on
    data:
      entity_id: light.plants
    service: light.turn_on
  alias: Sunrise Plants on
  condition: []
  id: '1509791350740'
  trigger:
  - event: sunrise
    platform: sun
- action:
  - alias: Plant Light off
    data:
      entity_id: light.plants
    service: light.turn_off
  alias: Sunset Plants off
  condition: []
  id: '1509791350741'
  trigger:
  - platform: sun
    event: sunset
- alias: Turn PC room lights on, on weekdays after pc started
  trigger:
  - platform: state
    entity_id: device_tracker.xmbombpc
    to: home
  condition:
  - condition: sun
    after: sunset
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
    service: script.turn_on
    data:
      entity_id: script.evening_pc_lights
  id: 0e1c561596ff4cf39d1eb0ad2e00053d
- alias: Turn PC TV on, on weekdays after coming home
  trigger:
  - platform: state
    entity_id: device_tracker.sm_n9500
    to: home
  condition:
  - condition: sun
    after: sunset
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
    service: switch.turn_on
    data:
      entity_id: switch.tv
  id: 0e1c561596ff4cf39d1eb0ad2e00053f
- action:
  - alias: PC Off TV Off
    data:
      entity_id: switch.tv
    service: switch.turn_off
  alias: PC Off TV Off
  id: pc-off-tv-off
  trigger:
  - entity_id: device_tracker.xmbombpc
    from: home
    platform: state
    to: not_home
- action:
  - alias: PC on TV on
    data:
      entity_id: switch.tv
    service: switch.turn_on
  alias: PC on TV on
  id: pc-on-tv-on
  trigger:
  - entity_id: device_tracker.xmbombpc
    from: not_home
    platform: state
    to: home
- action:
  - data:
      message: UPS DOWN!
    service: notify.pushbullet
  alias: UPS On Battery Notification
  condition: []
  id: '1511111478419'
  trigger:
  - entity_id: sensor.ups_status
    from: ONLINE
    platform: state
- action:
  - data:
      color_name: red
      entity_id: light.desk_leds
    service: light.turn_on
  alias: Desk LEDs red if turned on after sunset
  condition:
  - after: sunset
    condition: sun
  id: '1520076564952'
  trigger:
  - entity_id: light.desk_leds
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      color_name: blue
      entity_id: light.desk_leds
    service: light.turn_on
  alias: Desk LED blue if turned on before sunset
  condition:
  - before: sunset
    condition: sun
  id: '1520076624811'
  trigger:
  - entity_id: light.desk_leds
    from: 'off'
    platform: state
    to: 'on'
- action:
  - data:
      message: ZMain state changed
    service: notify.pushbullet
  alias: ZMain Degraded Notification
  condition: []
  id: '1511111478421'
  trigger:
  - entity_id: sensor.zfs_zmain_health
    from: ONLINE
    platform: state
- action:
  - data:
      message: ZBackup state changed
    service: notify.pushbullet
  alias: ZBackup Degraded Notification
  condition: []
  id: '1511111478420'
  trigger:
  - entity_id: sensor.zfs_zbackup_health
    from: ONLINE
    platform: state
- id: '1522953892250'
  alias: Bedroom Humidifier On
  trigger:
  - below: '45'
    entity_id: sensor.bedroom_humidity
    platform: numeric_state
  condition:
  - condition: state
    entity_id: group.milan_portable_devices
    state: home
  - after: '22:00'
    before: 08:00
    condition: time
  action:
  - data:
      entity_id: switch.humidifier
    service: switch.turn_on
- action:
  - data:
      entity_id: switch.humidifier
    service: switch.turn_off
  alias: Bedroom Humidifier off
  condition:
  - condition: state
    entity_id: group.milan_portable_devices
    state: home
  id: '1522954007709'
  trigger:
  - above: '45'
    entity_id: sensor.bedroom_humidity
    platform: numeric_state
- id: '1527534824288'
  alias: Desk LED Red if turned on and after sunset
  trigger:
  - event: sunset
    platform: sun
  condition:
  - condition: state
    entity_id: light.desk_leds
    state: 'on'
  action:
  - data:
      color_name: red
      entity_id: light.desk_leds
    service: light.turn_on
- id: '1537640292472'
  alias: Grower on
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.kitchen_grower_on.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition: []
  action:
  - data:
      entity_id:
      - light.kitchen_grower
    service: light.turn_on
- id: '1537640537656'
  alias: Grower off
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.kitchen_grower_off.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition: []
  action:
  - data:
      entity_id:
      - light.kitchen_grower
    service: light.turn_off
- alias: 2700K on
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.pc_room_hydro_2700k_on.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition: []
  action:
  - data:
      entity_id:
      - light.hydro_2700k
    service: light.turn_on
  id: bab9c47155a54b7ebbee5f58d7ba90e1
- alias: 2700K off
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.pc_room_hydro_2700k_off.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition: []
  action:
  - data:
      entity_id:
      - light.hydro_2700k
    service: light.turn_off
  id: 2a508e9e53344e35bd4accb6fec1cab4
- alias: LG OLED off after playing
  trigger:
  - platform: state
    entity_id: media_player.lg_4k_oled
    to: 'off'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: scene.turn_on
    entity_id: scene.living_room_normal
  id: 1daa736598934a179c35e6567ab173d0
- alias: LG OLED on
  trigger:
  - platform: state
    entity_id: media_player.lg_4k_oled
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: scene.turn_on
    entity_id: scene.watching_tv
  id: 7d0974f0e61643c3bad60f08f6923f8e
- alias: Cameras off if home
  trigger:
  - platform: state
    entity_id: group.milan_portable_devices
    to: home
    from: not_home
  action:
    service: switch.turn_off
    entity_id: group.fang_switches
  id: bdb1d72900f9459d8f3bbf0356b6bee1
- alias: Cameras on if not home
  trigger:
  - platform: state
    entity_id: group.milan_portable_devices
    to: not_home
    from: home
  action:
    service: switch.turn_on
    entity_id: group.fang_switches
  id: 5592c91d1d054c4485d26e673df10216
- alias: Lights off if not home
  trigger:
  - platform: state
    entity_id: group.milan_portable_devices
    to: not_home
    from: home
  action:
    service: light.turn_off
    entity_id: group.non_automatic_lights
  id: 25131da67fea4f56944935414680b6d1
- id: fbcbbbf751a84c0cb99e7a709aba8672
  alias: Lights on if home
  trigger:
  - entity_id: group.milan_portable_devices
    from: not_home
    platform: state
    to: home
  condition:
  - after: sunset
    condition: sun
  action:
  - entity_id: group.evening_lights
    service: light.turn_on
- id: 744b4b893020470d85a9a4f841d5114c
  alias: Alarm Clock by time
  trigger:
  - platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.bedroom_alarm_clock_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: state
    entity_id: device_tracker.sm_n9500
    state: home
  action:
  - entity_id: scene.bedroom_wake_up
    service: scene.turn_on
- alias: bed set
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.bed_mass
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.bed_mass
      above: 50
      below: 100
    - condition: state
      entity_id: device_tracker.sm_n9500
      state: home
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.in_bed
  id: a94c73122e7f4449bd600945188a3459
- alias: bed clear
  hide_entity: true
  trigger:
    platform: state
    entity_id: sensor.bed_mass
  condition:
    condition: and
    conditions:
    - condition: numeric_state
      entity_id: sensor.bed_mass
      below: 20
    - condition: state
      entity_id: device_tracker.sm_n9500
      state: home
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.in_bed
  id: 0b1a7bfdca5445dda5672f4987d1ec12
- alias: All Lights off (except bedroom corner) when in bed
  trigger:
    platform: state
    entity_id: input_boolean.in_bed
    to: 'on'
  condition:
    condition: and
    conditions:
    - condition: time
      after: '22:00:00'
      before: 02:30:00
  action:
  - service: script.turn_on
    entity_id: script.all_lights_off_except_bedroom
  id: 39542d047c5245e7a008c59c9f1385db
- id: '1541266912466'
  alias: Hydro Bubbler on
  trigger:
  - entity_id: group.milan_portable_devices
    platform: state
    to: not_home
  condition:
  - after: 06:00
    before: '22:00'
    condition: time
  action:
  - data:
      entity_id: switch.hydro_bubbler
    service: switch.turn_on
- id: '1541266912468'
  alias: Hydro Bubbler off
  trigger:
  - entity_id: device_tracker.sm_n9500
    platform: state
    to: home
  action:
  - data:
      entity_id: switch.hydro_bubbler
    service: switch.turn_off
- alias: Pause TV if light is turned on in another room
  trigger:
    platform: state
    from: 'off'
    to: 'on'
    entity_id: group.non_living_room_lights
  condition:
  - condition: state
    entity_id: media_player.lg_4k_oled
    state: playing
  action:
    service: media_player.media_pause
    entity_id: media_player.lg_4k_oled
  id: 104f6a021bae401391dfca5248b5096a
- alias: Set HA theme for day and night
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
    to: above_horizon
  - platform: state
    entity_id: sun.sun
    to: below_horizon
  action:
  - service_template: frontend.set_theme
    data_template:
      name: ' {% if states.sun.sun.state == "above_horizon" %} default {% else %}
        blue_night {% endif %}'
  id: 7f79bda228b441c2a156cfb409389b28
- alias: Send alert after daily vacuum to empty the dustbin
  trigger:
  - platform: state
    entity_id: group.milan_portable_devices
    to: home
    for:
      minutes: 5
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.daily_vacuum_first_run
      state: 'on'
    - condition: time
      after: 08:30:00
      before: '23:30:00'
    - condition: template
      value_template: "{% if states.automation.send_alert_after_daily_vacuum_to_empty_the_dustbin.last_triggered\
        \ is not none %}\n  {% if as_timestamp(now()) | int   -  as_timestamp(states.automation.send_alert_after_daily_vacuum_to_empty_the_dustbin.attributes.last_triggered)\
        \ | int > 1800 %} true {% else %} false\n  {% endif %}\n{% else %} false {%\
        \ endif %}\n"
    - condition: state
      entity_id: input_boolean.disable_dustbin_notification
      state: 'off'
  action:
  - service: notify.pushbullet
    data:
      message: Dustin is full :o
  id: f7d4984467bf4fc1b1bde60e39a6d8e9
- alias: Reset Daily Vacuum First Run state at midnight
  trigger:
  - platform: time
    at: 0:00:00
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.daily_vacuum_first_run
  id: 31078cb2ea0a4f6aad6c1a1dba41ed01
- alias: Start Daily Vacuum
  trigger:
  - platform: time_pattern
    minutes: /45
    seconds: 0
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: group.milan_portable_devices
      state: not_home
    - condition: state
      entity_id: input_boolean.daily_vacuum_first_run
      state: 'off'
    - condition: time
      after: '10:00:00'
      before: '19:00:00'
    - condition: state
      entity_id: input_boolean.disable_daily_vacuum
      state: 'off'
  action:
  - delay: 00:00:15
  - service: vacuum.start
    entity_id: vacuum.xiaomi_vacuum_cleaner
  - service: homeassistant.turn_on
    entity_id: input_boolean.daily_vacuum_first_run
  id: 9682f2eb9996425483a2fb8157fd2593
- id: '1578244687661'
  alias: Subwoofer off after 22:00
  trigger:
  - at: '22:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: switch.subwoofer
    service: switch.turn_off
- id: '1578244783554'
  alias: Subwoofer on if home
  trigger:
  - entity_id: group.milan_portable_devices
    platform: state
    to: home
  condition: []
  action:
  - data:
      entity_id: switch.subwoofer
    service: switch.turn_on
- id: '1578244853786'
  alias: Subwoofer off when leaving home
  trigger:
  - entity_id: group.milan_portable_devices
    platform: state
    to: not_home
  condition: []
  action:
  - data:
      entity_id: switch.subwoofer
    service: switch.turn_off
- id: '1578244945400'
  alias: Subwoofer on if TV is turned on before 22:00
  trigger:
  - entity_id: media_player.lg_4k_oled
    platform: state
    to: playing
  condition:
  - before: '22:00'
    condition: time
  action:
  - data:
      entity_id: switch.subwoofer
    service: switch.turn_on
