homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: 47.4008
  longitude: 8.6260

  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 450
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Zurich
  # Customization file
  customize: !include customize.yaml

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: xmb.li:8123
  trusted_networks:
    - 127.0.0.1
    - 192.168.1.0/24

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

apcupsd:
  host: 192.168.1.8

python_script:

led_color_temp:

weather:
  - platform: darksky
    api_key: !secret darksky

panel_iframe:
  nodered:
    title: Node-RED
    icon: mdi:sitemap
    url: http://xmb.li:1880
# Weather prediction
sensor:
  - platform: yr
    name: Weather now
    monitored_conditions:
      - symbol
      - temperature
      - precipitation
  - platform: time_date
    name: Bedroom Alarm Clock Time
    display_options:
      - 'time'
  - platform: apcupsd
    resources:
      - status
      - bcharge
      - timeleft
      - battv
      - nombattv
  - platform: hddtemp
    host: 192.168.1.8
    disks:
      - /dev/sda
      - /dev/sdb
      - /dev/sdc
      - /dev/sdd
      - /dev/sde
      - /dev/sdf
      - /dev/sdg
      - /dev/sdh
      - /dev/sdi
      - /dev/sdj
      - /dev/sdk
      - /dev/sdl
      - /dev/sdm
      - /dev/sdn
      - /dev/sdo
      - /dev/sdp
      - /dev/sdq
      - /dev/sdr
      - /dev/sds
      - /dev/sdt
      - /dev/sdu
  - platform: pi_hole
    host: 192.168.1.30
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today
      - unique_domains
      - dns_queries_today
      - domains_being_blocked
  - platform: speedtest
    # server_id: 6251
    monitored_conditions:
      - ping
      - download
      - upload
  - platform: bitcoin
    display_options:
      - exchangerate
  - platform: coinmarketcap
    currency: Bitcoin
    display_currency: CHF
  - platform: coinmarketcap
    currency: Ethereum
    display_currency: CHF
  - platform: coinmarketcap
    currency: Litecoin
    display_currency: CHF
  - platform: coinmarketcap
    currency: Dogecoin
    display_currency: CHF
  - platform: coinmarketcap
    currency: Garlicoin
    display_currency: CHF
  - platform: mqtt
    name: "Living Room Temperature"
    state_topic: "tele/sonoff/plants/SENSOR"
    unit_of_measurement: '°C'
    value_template: '{{ value_json["AM2301"]["Temperature"] }}'
  - platform: mqtt
    name: "Living Room Humidity"
    state_topic: "tele/sonoff/plants/SENSOR"
    unit_of_measurement: '%'
    value_template: '{{ value_json["AM2301"]["Humidity"] }}'
    icon: mdi:water-percent
  - platform: mqtt
    name: "Bedroom Temperature"
    state_topic: "tele/sonoff/bedroom/SENSOR"
    unit_of_measurement: '°C'
    value_template: '{{ value_json["AM2301"]["Temperature"] }}'
  - platform: mqtt
    name: "Bedroom Humidity"
    state_topic: "tele/sonoff/bedroom/SENSOR"
    unit_of_measurement: '%'
    value_template: '{{ value_json["AM2301"]["Humidity"] }}'
    icon: mdi:water-percent
  - platform: mqtt
    name: "Kitchen Temperature"
    state_topic: "tele/sonoff/grower/SENSOR"
    unit_of_measurement: '°C'
    value_template: '{{ value_json["AM2301"]["Temperature"] }}'
  - platform: mqtt
    name: "Kitchen Humidity"
    state_topic: "tele/sonoff/grower/SENSOR"
    unit_of_measurement: '%'
    value_template: '{{ value_json["AM2301"]["Humidity"] }}'
    icon: mdi:water-percent
  - platform: mqtt
    name: "Hydro 2700K Temperature"
    state_topic: "tele/sonoff/hydro_2700k/SENSOR"
    unit_of_measurement: '°C'
    value_template: '{{ value_json["AM2301"]["Temperature"] }}'
  - platform: mqtt
    name: "Hydro 2700K Humidity"
    state_topic: "tele/sonoff/hydro_2700k/SENSOR"
    unit_of_measurement: '%'
    value_template: '{{ value_json["AM2301"]["Humidity"] }}'
  - platform: mqtt
    name: "PC Room Temperature"
    state_topic: "tele/sonoff/pc_room_camera/SENSOR"
    unit_of_measurement: '°C'
    value_template: '{{ value_json["AM2301"]["Temperature"] }}'
  - platform: mqtt
    name: "PC Room Humidity"
    state_topic: "tele/sonoff/pc_room_camera/SENSOR"
    unit_of_measurement: '%'
    value_template: '{{ value_json["AM2301"]["Humidity"] }}'
    icon: mdi:water-percent
  - platform: mqtt
    state_topic: "/weight/bed/load"
    name: Bed Mass
    unit_of_measurement: "kg"

binary_sensor:
  - platform: threshold
    name: Shed Temperature Below 3.5
    entity_id: sensor.shed_temperature
    lower: 3.5
  - platform: threshold
    name: Shed Temperature Above 10
    entity_id: sensor.shed_temperature
    upper: 10

# Text to speech
tts:
  - platform: google

wake_on_lan:

media_player:
  - platform: plex
  - platform: spotify
    client_id: 521b6f020f9d4923a98c8bdb39889d03
    client_secret: !secret spotify_client_secret
  - platform: webostv
    host: 192.168.1.102
    name: LG 4K OLED
    turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
        mac: "20-3D-BD-1B-A3-86"
#    customize:
#      sources:
#        - youtube
#        - netflix

mqtt:
  broker: localhost
  discovery: true
  discovery_prefix: homeassistant

device_tracker:
  - platform: unifi
    host: 192.168.1.22
    username: !secret unifi_user
    password: !secret unifi_password
    verify_ssl: false

notify:
  - name: pushbullet
    platform: pushbullet
    api_key: !secret pushbullet_api_key
  - name: pushbullet_lis
    platform: pushbullet
    api_key: !secret pushbullet_api_key_lis

light:
  - platform: mqtt
    name: Plants
    state_topic: "stat/sonoff/plants/POWER"
    command_topic: "cmnd/sonoff/plants/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: Desk LEDs
    state_topic: "stat/sonoff/desk_leds/POWER"
    command_topic: "cmnd/sonoff/desk_leds/POWER"
    brightness_state_topic: "stat/sonoff/desk_leds/DIMMER"
    brightness_command_topic: "cmnd/sonoff/desk_leds/DIMMER"
    brightness_value_template: "{{ value_json.brightness }}"
    brightness_scale: 100
    rgb_state_topic: "stat/sonoff/desk_leds/COLOR"
    rgb_command_topic: "cmnd/sonoff/desk_leds/COLOR"
    rgb_command_template: "{{ '#%02x%02x%02x' | format(red, green, blue) }}"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: TV LEDs
    state_topic: "stat/sonoff/tv_leds/POWER"
    command_topic: "cmnd/sonoff/tv_leds/POWER"
    brightness_state_topic: "stat/sonoff/tv_leds/DIMMER"
    brightness_command_topic: "cmnd/sonoff/tv_leds/DIMMER"
    brightness_value_template: "{{ value_json.brightness }}"
    brightness_scale: 100
    rgb_state_topic: "stat/sonoff/tv_leds/COLOR"
    rgb_command_topic: "cmnd/sonoff/tv_leds/COLOR"
    rgb_command_template: "{{ '#%02x%02x%02x' | format(red, green, blue) }}"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: Kitchen Grower
    state_topic: "stat/sonoff/grower/POWER"
    command_topic: "cmnd/sonoff/grower/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: Living Room Dinner Table
    state_topic: "stat/sonoff/dinner_table/POWER"
    command_topic: "cmnd/sonoff/dinner_table/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: mqtt
    name: "Hydro 2700k"
    state_topic: "stat/sonoff/hydro_2700k/POWER"
    command_topic: "cmnd/sonoff/hydro_2700k/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
  - platform: flux_led
    automatic_add: true
    devices:
      192.168.1.174:
        name: Sofa LEDs
        mode: rgbw
      192.168.1.173:
        name: Bed LEDs
        mode: rgbw
      192.168.1.172:
        name: TV Monitor LEDs
        mode: rgbw

switch:
  - platform: mqtt
    name: "Hydro Bubbler"
    state_topic: "stat/sonoff/hydro_bubbler/POWER"
    command_topic: "cmnd/sonoff/hydro_bubbler/POWER"
  - platform: mqtt
    name: "TV"
    state_topic: "stat/sonoff/tv/POWER"
    command_topic: "cmnd/sonoff/tv/POWER"
  - platform: mqtt
    name: "PC Room Camera"
    state_topic: "stat/sonoff/pc_room_camera/POWER"
    command_topic: "cmnd/sonoff/pc_room_camera/POWER"
  - platform: mqtt
    name: "Hallway Camera"
    state_topic: "stat/sonoff/hallway_camera/POWER"
    command_topic: "cmnd/sonoff/hallway_camera/POWER"
  - platform: mqtt
    name: "Living Room Camera"
    state_topic: "stat/sonoff/living_room_camera/POWER"
    command_topic: "cmnd/sonoff/living_room_camera/POWER"
  - platform: wake_on_lan
    name: XMBomb PC
    mac_address: "70-4D-7B-B7-8B-DD"
  - platform: flux
    lights:
      - light.bed_leds
      - light.bedroom_corner_2
      - light.bedroom_panel
      - light.desk_leds
      - light.hallway_panel
      - light.kitchen_panel
      - light.living_room_panel
      - light.living_room_sofa
      - light.pc_room_monitors_2
      - light.pc_room_monitors_3
      - light.pc_room_panel_3
      - light.tradfri_bulb_e27_ws_opal_980lm_4
      - light.tv_leds

ffmpeg:

camera:
#  - platform: ffmpeg
#    name: PC Room Camera
#    input: rtsp://192.168.1.164:554/unicast
#  - platform: ffmpeg
#    name: Living Room Camera
#    input: rtsp://192.168.1.165:554/unicast
#  - platform: ffmpeg
#    name: Hallway Camera
#    input: rtsp://192.168.1.166:554/unicast
#  - platform: ffmpeg
#    name: DaFang
#    input: -rtsp_transport tcp -i rtsp://dafang:8554/unicast

input_datetime:
  bedroom_alarm_clock_time:
    name: Bedroom Alarm Clock
    has_date: false
    has_time: true

input_boolean:
  in_bed:
    name: Bed Occupancy
    initial: off
    icon: mdi:hotel

panel_custom:
  - name: floorplan
    sidebar_title: Floorplan
    sidebar_icon: mdi:home
    url_path: floorplan
    config: !include floorplan.yaml

zfs:

scene: !include scenes.yaml


group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
