resources:
  - type: module
    url: /local/mini-media-player-bundle.js?v=0.9.2
  - type: module
    url: /local/mini-graph-card-bundle.js?v=0.0.9
  - type: js
    url: /local/group-card.js?v=5
  - type: js
    url: /local/custom-group-card.js?v=16
  - type: js
    url: /local/slider-entity-row.js?v=1
  - type: js
    url: /local/vertical-stack-in-card.js?v=1

title: Home
views:
  - title: Main
    badges: 
      - device_tracker.sm_n9500
      - sensor.bitcoin
    cards:
      - type: weather-forecast
        entity: weather.dark_sky
        title: Weather
      - type: entities
        title: Cameras
        entities:
          - switch.pc_room_camera
          - switch.living_room_camera
          - switch.hallway_camera
      - type: glance
        entities:
          - switch.flux
      - type: entities
        title: Alarm Clock
        show_header_toggle: false
        entities:
          - input_datetime.bedroom_alarm_clock_time
          - automation.alarm_clock_by_time
      - type: entities
        entities:
          - script.all_lights_off_except_bedroom
          - scene.living_room_dinner
          - script.evening_pc_lights
      - type: map
        aspect_ratio: 16:9
        default_zoom: 10
        entities:
          - zone.home
          - device_tracker.sm_n9500
      - type: 'custom:custom-group-card'
        card:
          type: custom:slider-entity-row
          toggle: true
          title: Lights
        group: group.non_automatic_lights
      - type: custom:vertical-stack-in-card
        cards:
        - type: picture-elements
          icon: mdi:cloud
          title: "\u2655Dustin the third\u2655"
          image: '/local/vacuum1.jpg'
          elements:
            - type: icon
              icon: mdi:bell-ring
              tap_action: 
                action: call-service
                service: vacuum.locate
                service_data:
                  entity_id: vacuum.xiaomi_vacuum_cleaner
              entity: vacuum.xiaomi_vacuum_cleaner
              style:
                top: 90%
                left: 95%
                color: '#3090C7'
            - type: icon
              icon: mdi:crosshairs
              tap_action: 
                action: call-service
                service: vacuum.clean_spot
                service_data:
                  entity_id: vacuum.xiaomi_vacuum_cleaner
              entity: vacuum.xiaomi_vacuum_cleaner
              style:
                top: 90%
                left: 80%
                color: '#3090C7'
            - type: icon
              tap_action: 
                action: call-service
                service: vacuum.return_to_base
                service_data:
                  entity_id: vacuum.xiaomi_vacuum_cleaner
              icon: mdi:home
              entity: vacuum.xiaomi_vacuum_cleaner
              style:
                top: 90%
                left: 65%
                color: '#3090C7'
            - type: icon
              icon: mdi:stop
              tap_action: 
                action: call-service
                service: vacuum.stop
                service_data:
                  entity_id: vacuum.xiaomi_vacuum_cleaner
              entity: vacuum.xiaomi_vacuum_cleaner
              style:
                top: 90%
                left: 35%
                color: '#3090C7'
            - type: icon
              icon: mdi:pause
              tap_action: 
                action: call-service
                service: vacuum.pause
                service_data:
                  entity_id: vacuum.xiaomi_vacuum_cleaner
              entity: vacuum.xiaomi_vacuum_cleaner
              style:
                top: 90%
                left: 20%
                color: '#3090C7'
            - type: icon
              icon: mdi:play
              tap_action: 
                action: call-service
                service: vacuum.start
                service_data:
                  entity_id: vacuum.xiaomi_vacuum_cleaner
              entity: vacuum.xiaomi_vacuum_cleaner
              style:
                top: 90%
                left: 5%
                color: '#3090C7'
            - type: state-label
              entity: sensor.vacuum_operation
              style:
                top: 10%
                left: 1%
                color: rgb(255, 255, 255)
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 90%
                font-weight: bold
                border-color: rgb(34, 154, 210)
                background-color: '#3090C7'
                border-radius: 6px
            - type: state-label
              entity: sensor.vacuum_accessories
              style:
                top: 10%
                right: 1%
                color: rgb(255, 255, 255)
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 90%
                font-weight: bold
                border-color: rgb(34, 154, 210)
                background-color: '#3090C7'
                border-radius: 6px
            - type: state-label
              tap_action: more-info
              entity: vacuum.xiaomi_vacuum_cleaner
              style:
                top: 14%
                right: 38%
                color: rgb(255, 255, 255)
                transform: translate(0%,-50%)
                font-family: Trebuchet MS
                font-size: 150%
                font-weight: bold
                border-color: rgb(34, 154, 210)
                border-radius: 6px
                background-color: '#cccccc'
            - type: state-label
              entity: sensor.vacuum_cleanmainbrush
              style:
                top: 35%
                right: 1%
                color: '#ffffff'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 76%
                font-weight: bold
                border-right-style: solid
                border-color: rgb(34, 154, 210)
            - type: state-label
              entity: sensor.vacuum_cleansidebrush
              style:
                top: 45%
                right: 1%
                color: '#ffffff'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 76%
                font-weight: bold
                border-right-style: solid
                border-color: rgb(34, 154, 210)
            - type: state-label
              entity: sensor.vacuum_cleanfilter
              style:
                top: 55%
                right: 1%
                color: '#ffffff'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 76%
                font-weight: bold
                border-right-style: solid
                border-color: rgb(34, 154, 210)
                opacity: 0.8
            - type: state-label
              entity: sensor.vacuum_sensordirtyleft
              style:
                top: 65%
                right: 1%
                color: '#ffffff'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 76%
                font-weight: bold
                border-right-style: solid
                border-color: rgb(34, 154, 210)
            - type: state-label
              entity: sensor.vacuum_status
              style:
                top: 40%
                left: 1%
                color: '#ffffff'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 80%
                font-weight: bold
                border-left-style: solid
                border-color: '#3090C7'
            - type: state-label
              entity: sensor.vacuum_battery
              style:
                top: 50%
                left: 1%
                color: '#ffffff'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 80%
                font-weight: bold
                border-left-style: solid
                border-color: rgb(34, 154, 210)
            - type: state-label
              entity: sensor.vacuum_fan_speed
              style:
                top: 60%
                left: 1%
                color: '#ffffff'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 80%
                font-weight: bold
                border-left-style: solid
                border-color: rgb(34, 154, 210)
            - type: state-label
              entity: sensor.vacuum_cleaned_area
              prefix: "Area:"
              style:
                top: 79%
                left: 31%
                color: '#84a6ba'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 80%
                font-weight: bold
            - type: state-label
              entity: sensor.vacuum_cleaning_time
              prefix: "Time:"
              style:
                top: 79%
                left: 51%
                color: '#84a6ba'
                transform: translate(0%,-50%)
                pointer-events: none
                font-family: Trebuchet MS
                font-size: 80%
                font-weight: bold
        - type: glance
          columns: 2
          entities:
          - entity: input_boolean.disable_dustbin_notification
            name: Disable Notification
          - entity: input_boolean.disable_daily_vacuum
            name: Disable Daily Cleanup
        - type: history-graph
          entities:
            - vacuum.xiaomi_vacuum_cleaner
  - badges: []
    icon: 'mdi:sofa'
    path: living_room
    title: Living Room
    cards:
      - type: horizontal-stack
        cards:
          - entity: light.living_room_panel_2
            type: light
          - entity: light.living_room_dinner_table
            type: light
      - type: horizontal-stack
        cards:
          - entity: light.sofa_leds
            type: light
          - entity: light.tv_leds
            type: light
      - type: light
        entity: light.living_room_sofa
      - type: sensor
        entity: sensor.living_room_temperature
        graph: line
        detail: 2
      - type: entities
        entities:
          - scene.living_room_dinner
          - script.watching_tv_all_lights_off
          - light.plants
      - type: sensor
        entity: sensor.living_room_humidity
        graph: line
        detail: 2
      - type: sensor
        entity: sensor.living_room_mold_chance
        graph: line
        detail: 2
      # - type: sensor
      #   entity: sensor.greenhouse_humidity
      #   graph: line
      #   detail: 2
      # - type: sensor
      #   entity: sensor.greenhouse_temperature
      #   graph: line
        detail: 2
      - type: 'custom:mini-media-player'
        entity: media_player.lg_4k_oled
      - type: horizontal-stack
        cards:
          - entity: switch.subwoofer
            type:  entity-button
          - entity: sensor.subwoofer_current_power 
            type: sensor
            graph: line
            detail: 2
          - entity: sensor.subwoofer_total_power
            type: sensor
            graph: line
            detail: 2

  - title: PC Room
    icon: 'mdi:laptop'
    path: pc-room
    cards: 
      - type: horizontal-stack
        cards:
          - entity: light.pc_room_3d_printer_2
            type: light
          - entity: light.pc_room_monitors_2
            type: light
      - type: horizontal-stack
        cards:
          - entity: light.desk_leds
            type: light
          - entity: light.tv_monitor_leds
            type: light
      - type: light
        entity: light.pc_room_panel_2
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.pc_room_temperature
            graph: line
            detail: 2
          - type: sensor
            entity: sensor.pc_room_humidity
            graph: line
            detail: 2
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.hydro_2700k_temperature
            graph: line
            detail: 2
          - type: sensor
            entity: sensor.hydro_2700k_humidity
            graph: line
            detail: 2
          - type: entities
            entities:
              - input_datetime.pc_room_hydro_2700k_on
              - input_datetime.pc_room_hydro_2700k_off
      - type: sensor
        entity: sensor.pc_room_mold_chance
        graph: line
        detail: 2
      - type: entities
        entities:
          - switch.tv
          - switch.hydro_bubbler
          - light.hydro_2700k
          - script.evening_pc_lights
  - title: bedroom
    icon: 'mdi:hotel'
    path: bedroom
    badges: []
    cards: 
      - type: horizontal-stack
        cards:
          - entity: light.bedroom_corner
            type: light
          - entity: light.bed_leds
            type: light
      - type: light
        entity: light.bedroom_panel
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.bedroom_humidity
            graph: line
            detail: 2
          - type: sensor
            entity: sensor.bedroom_temperature
            graph: line
            detail: 2
      - type: vertical-stack
        cards:
          - type: sensor
            entity: sensor.bed_mass
            graph: line
            detail: 2
          - type: entities
            entities: 
              - input_boolean.in_bed
              - script.zero_bed
      - type: sensor
        entity: sensor.bedroom_mold_chance
        graph: line
        detail: 2
  - title: Hallway
    cards:      
      - type: light
        entity: light.hallway_panel
    icon: 'mdi:door'
    path: hallway
  - title: Kitchen
    cards:       
      - type: light
        entity: light.kitchen_panel
      - type: sensor
        entity: sensor.kitchen_temperature
        graph: line
        detail: 2
      - type: sensor
        entity: sensor.kitchen_humidity
        graph: line
        detail: 2
      - type: sensor
        entity: sensor.kitchen_mold_chance
        graph: line
        detail: 2
      - type: entities
        entities:
          - light.kitchen_grower
          - input_datetime.kitchen_grower_on
          - input_datetime.kitchen_grower_off
    icon: 'mdi:knife'
    path: kitchen
  - title: light_view
    badges: []
    cards:
      - entities:
          - light.bed_leds
          - light.bedroom_corner
          - light.bedroom_panel
          - light.desk_leds
          - light.hallway_panel
          - light.kitchen_panel
          - light.living_room_panel_2
          - light.living_room_sofa
          - light.living_room_dinner_table
          - light.pc_room_monitors_2
          - light.pc_room_panel_2
          - light.pc_room_3d_printer_2
          - light.tv_leds
          - light.sofa_leds
          - light.tv_monitor_leds
        title: All Lights
        type: entities
    icon: 'mdi:lightbulb'
    path: light_view
  - badges: []
    cards:
      - title: UPS
        type: glance
        entities:
          - sensor.ups_battery
          - sensor.ups_battery_nominal_voltage
          - sensor.ups_battery_voltage
          - sensor.ups_status
          - sensor.ups_time_left
      - title: Pandora HDD Sensors
        type: entities
        entities:
          - sensor.hd_temperature_dev_sda
          - sensor.hd_temperature_dev_sdb
          - sensor.hd_temperature_dev_sdc
          - sensor.hd_temperature_dev_sdd
          - sensor.hd_temperature_dev_sde
          - sensor.hd_temperature_dev_sdf
          - sensor.hd_temperature_dev_sdg
          - sensor.hd_temperature_dev_sdh
          - sensor.hd_temperature_dev_sdi
          - sensor.hd_temperature_dev_sdj
          - sensor.hd_temperature_dev_sdk
          - sensor.hd_temperature_dev_sdl
          - sensor.hd_temperature_dev_sdm
          - sensor.hd_temperature_dev_sdn
          - sensor.hd_temperature_dev_sdo
          - sensor.hd_temperature_dev_sdp
          - sensor.hd_temperature_dev_sdq
          - sensor.hd_temperature_dev_sdr
          - sensor.hd_temperature_dev_sdt
          - sensor.hd_temperature_dev_sdu
          - sensor.hd_temperature_dev_sdv
      - title: Pi Hole
        type: glance
        entities:
          - sensor.pi_hole_ads_blocked_today
          - sensor.pi_hole_ads_percentage_blocked_today
          - sensor.pi_hole_dns_queries_today
          - sensor.pi_hole_domains_blocked
      - title: ZBackup
        type: glance
        entities:
          - sensor.zfs_zbackup_alloc
          - sensor.zfs_zbackup_cap
          - sensor.zfs_zbackup_dedup
          - sensor.zfs_zbackup_frag
          - sensor.zfs_zbackup_free
          - sensor.zfs_zbackup_health
          - sensor.zfs_zbackup_size
      - title: ZMain
        type: glance
        entities:
          - sensor.zfs_zmain_alloc
          - sensor.zfs_zmain_cap
          - sensor.zfs_zmain_dedup
          - sensor.zfs_zmain_frag
          - sensor.zfs_zmain_free
          - sensor.zfs_zmain_health
          - sensor.zfs_zmain_size
      - entities:
          - sensor.bedroom_corner_remote
          - sensor.bedroom_remote_ceiling
          - sensor.hallway_remote
          - sensor.kitchen_remote
          - sensor.living_room_remote
          - sensor.living_room_sofa_remote
          - sensor.pc_room_monitors_remote
          - sensor.pc_room_remote
        title: TRADFRI Remotes
        type: entities
    icon: 'mdi:server'
    path: homelab_view
    title: homelab_view
  - badges: []
    cards:
      - entities:
          - device_tracker.galaxynote8
          - device_tracker.huawei_p10
        title: Milan and Linda
        type: entities
      - entities:
          - device_tracker.galaxynote8
          - device_tracker.sm_n9500
        title: Milan Portable Devices
        type: entities
      - entities:
          - device_tracker.slimtop
          - device_tracker.xmbombpc
        title: Milan Devices
        type: entities
      - entities:
          - device_tracker.huawei_p10
        title: Linda Portable Devices
        type: entities
    icon: 'mdi:account-multiple'
    path: people_view
    title: people_view

  - title: Automations
    path: automation_view
    cards:
      - type: 'custom:group-card'
        card:
          type: entities
          title: Automations
        group: group.all_automations
